# For each of these properties, except for rdf:type, 
# which different values do they take in those instances?

SELECT DISTINCT ?prop ?value
WHERE
{
 ?x rdf:type <http://dbpedia.org/ontology/Politician> .
 ?x ?prop ?value .
 filter ( ?prop not in ( rdf:type ) )
}
LIMIT 100

# query result: https://es.dbpedia.org/sparql?default-graph-uri=&query=SELECT+DISTINCT+%3Fprop+%3Fvalue%0D%0AWHERE%0D%0A%7B%0D%0A+%3Fx+rdf%3Atype+%3Chttp%3A%2F%2Fdbpedia.org%2Fontology%2FPolitician%3E+.%0D%0A+%3Fx+%3Fprop+%3Fvalue+.%0D%0A+filter+%28+%3Fprop+not+in+%28+rdf%3Atype+%29+%29%0D%0A%7D%0D%0ALIMIT+100&should-sponge=&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+

# first 10:
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Adame Ba Konaré"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Adriano Sánchez Roa"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Adrián Ward"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Agustín Haya de la Torre de la Rosa"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Agustín Molina Martínez"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Ahmed Hilmi Pasha"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Aileen Baviera"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Aisha Musa el-Said"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Akua Asabea Ayisi"@es
#   http://www.w3.org/2000/01/rdf-schema#label 	--> "Alain Vivien"@es
