### SPARQL queries

##

# Query 1: List all the properties used in our dataset

    SELECT DISTINCT
        ?Property
    WHERE {
        ?Subject ?Property ?Object .
    }
    ORDER BY asc(?Property)
    

# Result:

    http://www.schema.org#address
    http://www.schema.org#latitude
    http://www.schema.org#longitude
    http://www.semanticweb.org/group16/ontologies/air-quality#dateOfMeasure
    http://www.semanticweb.org/group16/ontologies/air-quality#districtID
    http://www.semanticweb.org/group16/ontologies/air-quality#inDistrict
    http://www.semanticweb.org/group16/ontologies/air-quality#measureCode
    http://www.semanticweb.org/group16/ontologies/air-quality#measureNotation
    http://www.semanticweb.org/group16/ontologies/air-quality#measureValue
    http://www.semanticweb.org/group16/ontologies/air-quality#measuredAt
    http://www.semanticweb.org/group16/ontologies/air-quality#measuredMagnitude
    http://www.semanticweb.org/group16/ontologies/air-quality#stationCode
    http://www.semanticweb.org/group16/ontologies/air-quality#streetID
    http://www.w3.org/1999/02/22-rdf-syntax-ns#type
    http://www.w3.org/2000/01/rdf-schema#comment
    http://www.w3.org/2000/01/rdf-schema#label
    http://www.w3.org/2002/07/owl#sameAs

##

# Query 2: List all the stations included in our dataset

    SELECT DISTINCT
        ?StLabel
    WHERE {
        ?St rdf:type ns:Station .
        ?St rdfs:label ?StLabel .
    }
    ORDER BY asc(?StLabel)

# Result:

    Arturo Soria
    Avda. Ramón y Cajal
    Barajas Pueblo
    Barrio del Pilar
    Casa de Campo
    Castellana
    Cuatro Caminos
    El Pardo
    Ensanche de Vallecas
    Escuelas Aguirre
    Farolillo
    Juan Carlos I
    Mendez Alvaro
    Moratalaz
    Parque del Retiro
    Plaza Castilla
    Pza. Elíptica
    Pza. de España
    Pza. del Carmen
    Sanchinarro
    Tres Olivos
    Urb. Embajada
    Vallecas
    Villaverde

##

# Query 3: List all the magnitudes measured in our dataset's stations

    SELECT DISTINCT
        ?Notation ?LabelEs ?LabelEn ?Code ?Description
    WHERE {
        ?Magnitude rdf:type ns:Magnitude .
        ?Magnitude rdfs:comment ?Description .
        ?Magnitude ns:measureNotation ?Notation .
        ?Magnitude ns:measureCode ?Code .
        ?Magnitude rdfs:label ?LabelEn , ?LabelEs .
            FILTER (LANG(?LabelEn) = 'en' && LANG(?LabelEs) = 'es')
    }
    ORDER BY xsd:integer(?Code)

# Result:

    SO2
    Dióxido de Azufre
    Sulfur dioxide
    Sulfur dioxide is a toxic gas responsible for the smell of burnt matches. It is released naturally by volcanic activity and is produced as a by-product of copper extraction and the burning of fossil fuels.
    1
    --
    CO
    Monóxido de Carbono
    Carbon monoxide
    Carbon monoxide is a colorless, odorless, and tasteless flammable gas that is slightly less dense than air. In the atmosphere, it is spatially variable and short-lived, having a role in the formation of ground-level ozone.
    6
    --
    NO
    Monóxido de Nitrógeno
    Nitric oxide (radical)
    Nitric oxide is a colorless gas. Nitric oxide is a free radical, i.e., it has an unpaired electron. An important intermediate in industrial chemistry, nitric oxide forms in combustion systems and can be generated by lightning in thunderstorms.
    7
    --
    NO2
    Dióxido de Nitrógeno
    Nitrogen dioxide
    Nitrogen dioxide is a chemical compound. NO2 is an intermediate in the industrial synthesis of nitric acid, millions of tons of which are produced each year for use primarily in the production of fertilizers. At higher temperatures it is a reddish-brown gas.
    8
    --
    PM2.5
    Partículas <2.5 μm
    Particulates <2.5 μm
    PM2.5 are very small particles in the air that have a diameter of 2.5 micrometers. Particulates, one of the six criteria for air pollutants of the U.S. EPA is a mixture that can include organic chemicals, dust, soot, and metals. These particles can come from all kinds of combustion, with that of cars, trucks, factories, wood burning, agricultural burning and other activities.
    9
    --
    PM10
    Partículas <10 μm
    Particulates <10 μm
    PM10 refers to small solid or liquid particles of dust, ash, soot, metallic particles, cement or pollen, dispersed in the atmosphere, and whose aerodynamic diameter is less than 10 µm. Air pollution by particulate matter is the alteration of the natural composition of the atmosphere as a consequence of the entry into suspension of particles, either by natural causes or by human action.
    10
    --
    NOx
    Óxidos de Nitrógeno
    Nitrogen oxide
    Nitric oxide is a colorless gas. Nitric oxide is a free radical, i.e., it has an unpaired electron. An important intermediate in industrial chemistry, nitric oxide forms in combustion systems and can be generated by lightning in thunderstorms.
    12
    --
    O3
    Ozono
    Ozone
    Ozone is an inorganic molecule. It is a pale blue gas with a distinctively pungent smell. Ozone is formed from dioxygen by the action of ultraviolet (UV) light and electrical discharges within the Earth's atmosphere. It is present in very low concentrations throughout the latter, with its highest concentration high in the ozone layer of the stratosphere, which absorbs most of the Sun's ultraviolet (UV) radiation.
    14
    --
    TOL
    Tolueno
    Toluene
    Toluene is an aromatic hydrocarbon. It is a colorless, water-insoluble liquid with the smell associated with paint thinners. Toluene is predominantly used as an industrial feedstock and a solvent.As the solvent in some types of paint thinner, permanent markers, contact cement and certain types of glue, toluene is sometimes used as a recreational inhalant.
    20
    --
    BEN
    Benceno
    Benzene
    Benzene is an organic chemical compound. Benzene is a colorless and highly flammable liquid with a sweet smell, and is responsible for the aroma around petrol (gasoline) stations. It is used primarily as a precursor to the manufacture of chemicals with more complex structure, such as ethylbenzene and cumene, of which billions of kilograms are produced annually.
    30
    --
    EBE
    Etilbenceno
    Ethylbenzene
    Ethylbenzene is an organic compound. It is a highly flammable, colorless liquid with an odor similar to that of gasoline. This monocyclic aromatic hydrocarbon is important in the petrochemical industry as an intermediate in the production of styrene, the precursor to polystyrene, a common plastic material.
    35
    --
    TCH
    Hidrocarburos totales (hexano)
    Hexane
    Hexane is a straight-chain alkane. Hexane is a significant constituent of gasoline. It is a colorless liquid, odorless when pure, and with boiling points approximately 69 °C. It is widely used as a cheap, relatively safe, largely unreactive, and easily evaporated non-polar solvent.
    42
    --
    CH4
    Metano
    Methane
    Methane is a chemical compound and is the main constituent of natural gas. The relative abundance of methane on Earth makes it an economically attractive fuel, although capturing and storing it poses technical challenges due to its gaseous state under normal conditions for temperature and pressure.
    43
    --
    NMHC
    Hidrocarburos no metánicos (hexano)
    Non-Methane volatile organic compound
    Non-Methane Volatile Organic Compounds (NMVOC) do not include methane (CH4), since its reactivity in the atmosphere is negligible. NMVOCs (mainly hydrocarbons) cause the formation of tropospheric ozone by reacting with sunlight.
    44
    --


##

# Query 4: List all the measures linked to an specific station

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?St rdf:type ns:Station .
        ?St rdfs:label "Moratalaz"^^<http://www.w3.org/2001/XMLSchema#string> .
        ?Measure rdf:type ns:Measurement .
        ?Measure ns:measuredAt ?St .
    }

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/36_7_28079036_2017_7_24
    http://www.semanticweb.org/group16/air-quality/resource/36_6_28079036_2016_9_11
    http://www.semanticweb.org/group16/air-quality/resource/36_8_28079036_2018_12_26
    http://www.semanticweb.org/group16/air-quality/resource/36_12_28079036_2010_5_16
    http://www.semanticweb.org/group16/air-quality/resource/36_1_28079036_2015_3_15
    http://www.semanticweb.org/group16/air-quality/resource/36_12_28079036_2012_2_23

##

# Query 5: List all the measures given an specific day

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?Measure rdf:type ns:Measurement .
        ?Measure ns:dateOfMeasure ?Date .
            FILTER REGEX (STR(?Date), "^2016-04-27", "i") 
    }

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/59_14_28079059_2016_4_27

##

# Query 6: List all the measures given an specific magnitude

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?Measure rdf:type ns:Measurement .
        ?Magnitude rdf:type ns:Magnitude .
        ?Magnitude rdfs:label ?Label .
            FILTER (LANG(?Label) = 'en' && REGEX(?Label, "Sulfur dioxide", "i"))
        ?Measure ns:measuredMagnitude ?Magnitude .
    }

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/38_1_28079038_2019_1_11
    http://www.semanticweb.org/group16/air-quality/resource/35_1_28079035_2017_4_9
    http://www.semanticweb.org/group16/air-quality/resource/17_1_28079017_2018_8_9
    http://www.semanticweb.org/group16/air-quality/resource/8_1_28079008_2018_10_2
    http://www.semanticweb.org/group16/air-quality/resource/17_1_28079017_2011_5_27
    http://www.semanticweb.org/group16/air-quality/resource/18_1_28079018_2015_11_17
    http://www.semanticweb.org/group16/air-quality/resource/18_1_28079018_2010_6_3
    http://www.semanticweb.org/group16/air-quality/resource/36_1_28079036_2015_3_15
    http://www.semanticweb.org/group16/air-quality/resource/40_1_28079040_2018_7_29
    http://www.semanticweb.org/group16/air-quality/resource/18_1_28079018_2014_7_30
    http://www.semanticweb.org/group16/air-quality/resource/24_1_28079024_2016_6_14
    http://www.semanticweb.org/group16/air-quality/resource/4_1_28079004_2012_7_4
    http://www.semanticweb.org/group16/air-quality/resource/8_1_28079008_2011_7_3
    http://www.semanticweb.org/group16/air-quality/resource/17_1_28079017_2013_1_18
    http://www.semanticweb.org/group16/air-quality/resource/18_1_28079018_2012_7_10

##

# Query 7: List all the measures in a given district

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?St rdf:type ns:Station .
        ?St ns:inDistrict ?District .
        ?District owl:sameAs <https://www.wikidata.org/wiki/Q807230> .
        ?Measure rdf:type ns:Measurement .
        ?Measure ns:measuredAt ?St .
    }

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/55_8_28079055_2014_4_29
    http://www.semanticweb.org/group16/air-quality/resource/55_20_28079055_2017_3_26
    http://www.semanticweb.org/group16/air-quality/resource/55_12_28079055_2016_6_28
    http://www.semanticweb.org/group16/air-quality/resource/55_8_28079055_2011_10_21
    http://www.semanticweb.org/group16/air-quality/resource/55_35_28079055_2012_7_21
    http://www.semanticweb.org/group16/air-quality/resource/55_10_28079055_2015_6_10
    http://www.semanticweb.org/group16/air-quality/resource/55_8_28079055_2013_5_23
    http://www.semanticweb.org/group16/air-quality/resource/55_44_28079055_2013_9_21
    http://www.semanticweb.org/group16/air-quality/resource/55_8_28079055_2010_11_24
    http://www.semanticweb.org/group16/air-quality/resource/55_43_28079055_2019_4_18
    http://www.semanticweb.org/group16/air-quality/resource/55_30_28079055_2018_8_6
    http://www.semanticweb.org/group16/air-quality/resource/59_12_28079059_2014_9_3
    http://www.semanticweb.org/group16/air-quality/resource/59_12_28079059_2010_8_28
    http://www.semanticweb.org/group16/air-quality/resource/59_8_28079059_2013_4_3
    http://www.semanticweb.org/group16/air-quality/resource/59_12_28079059_2015_6_29
    http://www.semanticweb.org/group16/air-quality/resource/59_14_28079059_2016_4_27
    http://www.semanticweb.org/group16/air-quality/resource/59_8_28079059_2011_10_2
    http://www.semanticweb.org/group16/air-quality/resource/27_42_28079027_2013_8_9
    http://www.semanticweb.org/group16/air-quality/resource/27_8_28079027_2014_12_26
    http://www.semanticweb.org/group16/air-quality/resource/27_8_28079027_2012_9_19
    http://www.semanticweb.org/group16/air-quality/resource/27_42_28079027_2011_9_5
    http://www.semanticweb.org/group16/air-quality/resource/27_8_28079027_2015_11_4
    http://www.semanticweb.org/group16/air-quality/resource/27_8_28079027_2010_12_5
    http://www.semanticweb.org/group16/air-quality/resource/27_14_28079027_2016_2_7

##

# Query 8: List all the measures taken in 2014

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?Measure rdf:type ns:Measurement .
        ?Measure ns:dateOfMeasure ?Date .
            FILTER REGEX (STR(?Date), "^2014", "i") 
    }
    ORDER BY asc(?Date)

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/18_35_28079018_2014_1_4
    http://www.semanticweb.org/group16/air-quality/resource/50_9_28079050_2014_1_9
    http://www.semanticweb.org/group16/air-quality/resource/11_7_28079011_2014_1_29
    http://www.semanticweb.org/group16/air-quality/resource/56_7_28079056_2014_2_16
    http://www.semanticweb.org/group16/air-quality/resource/24_14_28079024_2014_4_19
    http://www.semanticweb.org/group16/air-quality/resource/39_7_28079039_2014_4_28
    http://www.semanticweb.org/group16/air-quality/resource/55_8_28079055_2014_4_29
    http://www.semanticweb.org/group16/air-quality/resource/16_8_28079016_2014_5_3
    http://www.semanticweb.org/group16/air-quality/resource/57_10_28079057_2014_6_15
    http://www.semanticweb.org/group16/air-quality/resource/40_12_28079040_2014_7_17
    http://www.semanticweb.org/group16/air-quality/resource/18_1_28079018_2014_7_30
    http://www.semanticweb.org/group16/air-quality/resource/35_14_28079035_2014_8_28
    http://www.semanticweb.org/group16/air-quality/resource/59_12_28079059_2014_9_3
    http://www.semanticweb.org/group16/air-quality/resource/4_6_28079004_2014_9_19
    http://www.semanticweb.org/group16/air-quality/resource/48_9_28079048_2014_10_7
    http://www.semanticweb.org/group16/air-quality/resource/38_7_28079038_2014_11_16
    http://www.semanticweb.org/group16/air-quality/resource/8_9_28079008_2014_12_19
    http://www.semanticweb.org/group16/air-quality/resource/27_8_28079027_2014_12_26

##

# Query 9: List the measures given a magnitude and a range value

    SELECT DISTINCT
        ?Measure
    WHERE {
        ?Measure rdf:type ns:Measurement .
        ?Magnitude rdf:type ns:Magnitude .
        ?Magnitude rdfs:label ?Label .
            FILTER (LANG(?Label) = 'en' && REGEX(?Label, "Nitrogen oxide", "i"))
        ?Measure ns:measuredMagnitude ?Magnitude .
        ?Measure ns:measureValue ?Value .
            FILTER (?Value >= 100)
    }

# Result:

    http://www.semanticweb.org/group16/air-quality/resource/11_12_28079011_2013_10_21
    http://www.semanticweb.org/group16/air-quality/resource/36_12_28079036_2012_2_23
    http://www.semanticweb.org/group16/air-quality/resource/57_12_28079057_2016_1_23
    http://www.semanticweb.org/group16/air-quality/resource/8_12_28079008_2016_10_1
    http://www.semanticweb.org/group16/air-quality/resource/49_12_28079049_2018_1_30
    http://www.semanticweb.org/group16/air-quality/resource/40_12_28079040_2011_11_7
    http://www.semanticweb.org/group16/air-quality/resource/50_12_28079050_2017_12_13
