PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  ont:  <http://linkeddata.es/group09/ontology/TrafficAccident#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  owl:  <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT  ?district ?district_wikidata
WHERE
  { ?accident  rdf:type      ont:Accident ;
              ont:occursOn   ?streetcrossing .
    ?streetcrossing
              ont:locatedIn  ?district_csv .
    ?district_csv
              rdfs:label     ?district ;
              owl:sameAs     ?district_wikidata
  }