# -*- coding: utf-8 -*-
"""Task01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PgJkwN15RJEcWKTN0EL5-Ixrcdj6Cw92

**Task 01: Reading and writing RDF files**

Leer y escribir ficheros que contienen tripletas es muy sencillo en RDFlib, para ello vamos a emplear dos métodos de la librería: parse y serialize.
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4"

from rdflib import Graph, Namespace, Literal
g = Graph()

"""Podemos añadir tripletas a nuestro grafo empleando *parse*, que leerá el recurso proporcionado. Debemos además indicarle el formato si este no puede ser inferido."""

g.parse(github_storage+"/resources/example1.rdf", format="xml")

"""Para visualizar el grafo en un formato específico podemos utilizar *serialize*. Por ejemplo aquí mostramos la salida del grafo en turtle"""

print(g.serialize(format="ttl").decode("UTF-8"))

"""El recurso puede ser local o remoto, como en nuestro caso. El resultado es el mismo. Podemos añadir todos los datos que queramos a nuestro grafo, los datos simplemente se irán fusionando."""

g.parse(github_storage+"/resources/example2.rdf", format="xml")

"""Ahora podemos comprobar el resultado volcando las tripletas de forma sencilla."""

for subj, pred, obj in g:
  print(subj,pred,obj)

"""Ahora podemos ver la operación inversa, serializando estos datos a algún formato que nos lo permita. Este proceso también nos permite una conversión sencilla entre formatos."""

print(g.serialize(format="xml").decode("UTF-8"))

"""También podemos guardar el resultado serializado en un fichero, puedes ver este fichero resultante en el panel izquierdo."""

g.serialize("example1.ttl", format="ttl")