# -*- coding: utf-8 -*-
"""Task00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q9Is3iUuRD5kgFbYmXTN0vjjp02Ley5X

**Task 00: Installing and testing RDFlib**

Instalamos las dependencias necesarias en nuestro entorno. `pip` es el gestor de paquetes de Python.
"""

!pip install rdflib

"""Del paquete rdflib importamos las clases necesarias para la tarea"""

from rdflib import Graph, Namespace, Literal

"""Creamos un grafo vacío"""

g = Graph()

"""Creamos un espacio de nombres"""

app_ns = Namespace("http://example.org/App/")

"""Definimos el sujeto, predicado y objeto de la tripleta que vamos a insertar"""

app = app_ns.this
says = app_ns.says
hello = Literal("Hola mundo!")

"""En RDFlib las tripletas se definen como una tupla nativa de Python que contiene 3 elementos en el orden (sujeto, predicado y objeto)."""

triple = (app, says, hello)
g.add(triple)

"""Podemos iterar sobre nuestro grafo para obtener todas las tripletas almacenadas, con la función g.triples() podemos buscar las que coincidan con el patrón especificado. Indicamos None donde nos sea indiferente el resultado.

Doc: https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.Graph.triples
"""

search = g.triples((None, says, None))

for subj, pred, obj in search:
  print(subj,pred,obj)

"""Adicionalmenta también podemos mostrar todas las tripletas serializando nuestro grafo en alguno de los formato soportados."""

#@title
print(g.serialize(format="xml").decode("UTF-8"))