PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX owl: http://www.w3.org/2002/07/owl#
PREFIX rdfs: http://www.w3.org/2000/01/rdf-schema#
PREFIX classes: http://scooters.com/Group12/Classes/

#Query for retrieving the links of all the neighbourhoods in Madrid
SELECT DISTINCT ?neighbourhood ?linkWikidata
	WHERE {
		?neighbourhood rdf:type classes:Neighbourhood.
		?neighbourhood owl:sameAs ?linkWikidata.
	}

#Query for retrieving the links of all the districts in Madrid
SELECT DISTINCT ?district ?linkWikidata
	WHERE {
		?district rdf:type classes:District.
		?district owl:sameAs ?linkWikidata.
	}
