# -*- coding: utf-8 -*-
"""Task08.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/18P0xTS31q1P7nR4efg0Yy3QrClOxqMAe
**Task 08: Completing missing data**
"""

github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2020-2021/master/Assignment4/"

from rdflib import Graph, Namespace, Literal, URIRef, RDF, RDFS, FOAF, XSD
from rdflib.plugins.sparql import prepareQuery
g1 = Graph()
g2 = Graph()
g1.parse("../resources/data01.rdf", format="xml")
g2.parse("../resources/data02.rdf", format="xml")

g1.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g1.namespace_manager.bind('ns', Namespace("http://data.org#"), override=False)
g2.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g2.namespace_manager.bind('ns', Namespace("http://data.org#"), override=False)

ns = Namespace("http://data.org#")
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""
q1 = prepareQuery('''
  SELECT 
    ?s ?p ?o
  WHERE { 
    ?s rdf:type ns:Person.
    ?s ?p ?o
  }
  ''',
  initNs = {"ns": ns, "rdf":RDF,"rdfs":RDFS}
)
for r in g1.query(q1):
  print(r)

g1.add((ns.SaraJones,,))