PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?PROVINCIA
WHERE
{
  ?PROVINCIA rdf:type <http://www.wsdl.org/grupo17/ontology/PROVINCIA>
  ?PROVINCIA  owl:sameAs <https://www.wikidata.org/wiki/Q24004405>
}

