package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

import controlador.Controller;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jmdia
 */
public class Searcher extends javax.swing.JFrame {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static Controller c;

	private String tipoAccidente_seleccionado;
	private String rangoEdad_seleccionado;
	private String sexo_seleccionado_seleccionado;
	private String gradoLesion_seleccionado;
	private String mes_seleccionado;
	private String distrito_seleccionado;
	private String vehiculo_seleccionado;
	private String intervaloHora_seleccionado;
	private String weather_seleccionado;
	private String n_results;

	/**
	 * Creates new form Searcher
	 */
	public Searcher() {
		c = MainWindow.getC();
		inicializarIcono();
		initComponents();
		anadirItemBoxes();
	}
	private void inicializarIcono() {
		ImageIcon icono = new ImageIcon("resources/ico.png");
		this.setIconImage(icono.getImage());
	}
	private void anadirItemBoxes() {
		jComboBox_TypeOfAccident.addItem("NO FILTER"); 
		jComboBox_AgeRange.addItem("NO FILTER"); 
		jComboBox_Sex.addItem("NO FILTER"); 
		jComboBox_District.addItem("NO FILTER"); 
		jComboBox_InjuryStatus.addItem("NO FILTER"); 
		jComboBox_Month.addItem("NO FILTER"); 
		jComboBox_VehicleInvolved.addItem("NO FILTER"); 
		jComboBox_Weather.addItem("NO FILTER"); 
		jComboBox_HourInterval.addItem("NO FILTER"); 


		for(int i = 0;i<c.getE().getTiposAccidente().size();i++){
			jComboBox_TypeOfAccident.addItem(c.getE().getTiposAccidente().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposRangoEdad().size();i++){
			jComboBox_AgeRange.addItem(c.getE().getTiposRangoEdad().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposSexo().size();i++){
			jComboBox_Sex.addItem(c.getE().getTiposSexo().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposDistrito().size();i++){
			jComboBox_District.addItem(c.getE().getTiposDistrito().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposGradoLesion().size();i++){
			jComboBox_InjuryStatus.addItem(c.getE().getTiposGradoLesion().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposMes().size();i++){
			jComboBox_Month.addItem(c.getE().getTiposMes().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposVehiculo().size();i++){
			jComboBox_VehicleInvolved.addItem(c.getE().getTiposVehiculo().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposWeather().size();i++){
			jComboBox_Weather.addItem(c.getE().getTiposWeather().get(i).toString());
		}
		for(int i = 0;i<c.getE().getTiposIntervaloHora().size();i++){
			jComboBox_HourInterval.addItem(c.getE().getTiposIntervaloHora().get(i).toString());
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		this.tipoAccidente_seleccionado = "NO FILTER";
		this.distrito_seleccionado = "NO FILTER";
		this.gradoLesion_seleccionado = "NO FILTER";
		this.intervaloHora_seleccionado = "NO FILTER";
		this.mes_seleccionado = "NO FILTER";
		this.n_results = "5";
		this.rangoEdad_seleccionado = "NO FILTER";
		this.sexo_seleccionado_seleccionado = "NO FILTER";
		this.vehiculo_seleccionado = "NO FILTER";
		this.weather_seleccionado = "NO FILTER";

		jLabelTitle = new javax.swing.JLabel();
		jLabelColorBar = new javax.swing.JLabel();
		jLabelText = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabelText1 = new javax.swing.JLabel();
		jComboBox_TypeOfAccident = new javax.swing.JComboBox<>();
		jLabelText2 = new javax.swing.JLabel();
		jLabelText3 = new javax.swing.JLabel();
		jComboBox_AgeRange = new javax.swing.JComboBox<>();
		jLabelText4 = new javax.swing.JLabel();
		jComboBox_Sex = new javax.swing.JComboBox<>();
		jLabelText5 = new javax.swing.JLabel();
		jLabelText6 = new javax.swing.JLabel();
		jLabelText7 = new javax.swing.JLabel();
		jComboBox_District = new javax.swing.JComboBox<>();
		jComboBox_InjuryStatus = new javax.swing.JComboBox<>();
		jComboBox_Month = new javax.swing.JComboBox<>();
		jLabelText8 = new javax.swing.JLabel();
		jComboBox_VehicleInvolved = new javax.swing.JComboBox<>();
		jLabelText9 = new javax.swing.JLabel();
		jComboBox_Weather = new javax.swing.JComboBox<>();
		jLabelText10 = new javax.swing.JLabel();
		jComboBox_HourInterval = new javax.swing.JComboBox<>();
		jButtonSearch = new javax.swing.JButton();
		jLabelResults = new javax.swing.JLabel();
		jComboBox_NumberResults = new javax.swing.JComboBox<>();


		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(500, 200));
		setPreferredSize(new java.awt.Dimension(800, 650));

		jLabelTitle.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
		jLabelTitle.setText("Searcher");

		jLabelColorBar.setBackground(new java.awt.Color(0, 0, 0));
		jLabelColorBar.setOpaque(true);

		jLabelText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabelText.setText("CATEGORIES");

		jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel1.setText("<html>- You can search for accidents by filtering by various categories.</html> ");

		jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel2.setText("<html>- You have to select at least one item from each category.</html> ");

		jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabel3.setText("<html>- Otherwise, the search will be done with the items that are by default.</html>");

		jLabelText1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
		jLabelText1.setText("HOW TO SEARCH");

		jComboBox_TypeOfAccident.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_TypeOfAccident.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_TypeOfAccidentActionPerformed(evt);
			}
		});

		jLabelText2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText2.setText("Type of accident:");

		jLabelText3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText3.setText("Age Range:");

		jComboBox_AgeRange.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_AgeRange.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_AgeRangeActionPerformed(evt);
			}
		});

		jLabelText4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText4.setText("Sex:");

		jComboBox_Sex.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_Sex.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_SexActionPerformed(evt);
			}
		});

		jLabelText5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText5.setText("Injury Status:");

		jLabelText6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText6.setText("Month:");

		jLabelText7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText7.setText("District:");

		jComboBox_District.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_District.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_DistrictActionPerformed(evt);
			}
		});

		jComboBox_InjuryStatus.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_InjuryStatus.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_InjuryStatusActionPerformed(evt);
			}
		});

		jComboBox_Month.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_Month.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_MonthActionPerformed(evt);
			}
		});

		jLabelText8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText8.setText(" Vehicle Involved:");

		jComboBox_VehicleInvolved.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_VehicleInvolved.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_VehicleInvolvedActionPerformed(evt);
			}
		});

		jLabelText9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText9.setText("Hour Interval:");

		jComboBox_Weather.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_Weather.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_WeatherActionPerformed(evt);
			}
		});

		jLabelText10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelText10.setText("Weather:");

		jComboBox_HourInterval.setModel(new javax.swing.DefaultComboBoxModel<>());
		jComboBox_HourInterval.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_HourIntervalActionPerformed(evt);
			}
		});

		jButtonSearch.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		jButtonSearch.setText("SEARCH");
		jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonSearchActionPerformed(evt);
			}
		});

		jLabelResults.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
		jLabelResults.setText("Max number of results to show: ");

		jComboBox_NumberResults.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"5", "10", "20", "30", "50","100","200","300","400","500"}));
		jComboBox_NumberResults.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_NumberResultsActionPerformed(evt);
			}
		});
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jLabelColorBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addContainerGap()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGroup(layout.createSequentialGroup()
																		.addGap(10, 10, 10)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(layout.createSequentialGroup()
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(layout.createSequentialGroup()
																										.addComponent(jLabelText2)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(jComboBox_TypeOfAccident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGroup(layout.createSequentialGroup()
																										.addGap(27, 27, 27)
																										.addComponent(jLabelText5)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(jComboBox_InjuryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGap(18, 18, 18)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(jLabelText3)
																								.addComponent(jLabelText6))
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(jComboBox_AgeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(jComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGap(22, 22, 22)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																								.addComponent(jLabelText7)
																								.addComponent(jLabelText4))
																						.addGap(18, 18, 18)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(jComboBox_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addComponent(jComboBox_District, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
																.addGroup(layout.createSequentialGroup()
																		.addGap(7, 7, 7)
																		.addComponent(jLabelText8)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jComboBox_VehicleInvolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jLabelText9)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(jComboBox_HourInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18, 18, 18)
																		.addComponent(jLabelText10)
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(jComboBox_Weather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(0, 0, Short.MAX_VALUE))))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(148, 148, 148)
														.addComponent(jLabelResults, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(jComboBox_NumberResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addGap(258, 258, 258)
														.addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap())
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(22, 22, 22)
								.addComponent(jLabelText1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(464, Short.MAX_VALUE)))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabelColorBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(61, 61, 61)
						.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabelText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelText2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_TypeOfAccident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_AgeRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelText5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_InjuryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_District, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelText8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_VehicleInvolved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_HourInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelText10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jComboBox_Weather, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jComboBox_NumberResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(42, 42, 42))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(105, 105, 105)
								.addComponent(jLabelText1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(491, Short.MAX_VALUE)))
				);

		jLabelTitle.setHorizontalAlignment(SwingConstants.CENTER);
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
		c.getE().setDatosCargados(true);
		c.getE().setDatosRecibidos(true);
		c.setS(this);
		new Controller();
		if(c.getE().getNumerodeFilas() == 0) {
			JOptionPane.showMessageDialog(null, "There are no results with that values. Please search again with other values.", "No results available", JOptionPane.INFORMATION_MESSAGE);
		}
		else {
			new Result().setVisible(true);
			this.setVisible(false);
		}
	}//GEN-LAST:event_jButtonSearchActionPerformed

	private void jComboBox_WeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_WeatherActionPerformed
		this.weather_seleccionado = jComboBox_Weather.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_WeatherActionPerformed

	private void jComboBox_NumberResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NumberResultsActionPerformed
		this.n_results = jComboBox_NumberResults.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_NumberResultsActionPerformed

	private void jComboBox_HourIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_HourIntervalActionPerformed
		this.intervaloHora_seleccionado =jComboBox_HourInterval.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_HourIntervalActionPerformed

	private void jComboBox_VehicleInvolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_VehicleInvolvedActionPerformed
		this.vehiculo_seleccionado = jComboBox_VehicleInvolved.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_VehicleInvolvedActionPerformed

	private void jComboBox_DistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_DistrictActionPerformed
		this.distrito_seleccionado = jComboBox_District.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_DistrictActionPerformed

	private void jComboBox_MonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MonthActionPerformed
		this.mes_seleccionado = jComboBox_Month.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_MonthActionPerformed

	private void jComboBox_InjuryStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_InjuryStatusActionPerformed
		this.gradoLesion_seleccionado =  jComboBox_InjuryStatus.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_InjuryStatusActionPerformed

	private void jComboBox_TypeOfAccidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TypeOfAccidentActionPerformed
		this.tipoAccidente_seleccionado = jComboBox_TypeOfAccident.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_TypeOfAccidentActionPerformed

	private void jComboBox_AgeRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_AgeRangeActionPerformed
		this.rangoEdad_seleccionado = jComboBox_AgeRange.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_AgeRangeActionPerformed

	private void jComboBox_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_SexActionPerformed
		this.sexo_seleccionado_seleccionado = jComboBox_Sex.getSelectedItem().toString();
	}//GEN-LAST:event_jComboBox_SexActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new Searcher().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonSearch;
	private javax.swing.JComboBox<String> jComboBox_AgeRange;
	private javax.swing.JComboBox<String> jComboBox_District;
	private javax.swing.JComboBox<String> jComboBox_HourInterval;
	private javax.swing.JComboBox<String> jComboBox_InjuryStatus;
	private javax.swing.JComboBox<String> jComboBox_Month;
	private javax.swing.JComboBox<String> jComboBox_NumberResults;
	private javax.swing.JComboBox<String> jComboBox_Sex;
	private javax.swing.JComboBox<String> jComboBox_TypeOfAccident;
	private javax.swing.JComboBox<String> jComboBox_VehicleInvolved;
	private javax.swing.JComboBox<String> jComboBox_Weather;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabelColorBar;
	private javax.swing.JLabel jLabelResults;
	private javax.swing.JLabel jLabelText;
	private javax.swing.JLabel jLabelText1;
	private javax.swing.JLabel jLabelText10;
	private javax.swing.JLabel jLabelText2;
	private javax.swing.JLabel jLabelText3;
	private javax.swing.JLabel jLabelText4;
	private javax.swing.JLabel jLabelText5;
	private javax.swing.JLabel jLabelText6;
	private javax.swing.JLabel jLabelText7;
	private javax.swing.JLabel jLabelText8;
	private javax.swing.JLabel jLabelText9;
	private javax.swing.JLabel jLabelTitle;
	// End of variables declaration//GEN-END:variables

	public String getTipoAccidente_seleccionado() {
		return tipoAccidente_seleccionado;
	}
	public void setTipoAccidente_seleccionado(String tipoAccidente_seleccionado) {
		this.tipoAccidente_seleccionado = tipoAccidente_seleccionado;
	}
	public String getRangoEdad_seleccionado() {
		return rangoEdad_seleccionado;
	}
	public void setRangoEdad_seleccionado(String rangoEdad_seleccionado) {
		this.rangoEdad_seleccionado = rangoEdad_seleccionado;
	}
	public String getSexo_seleccionado_seleccionado() {
		return sexo_seleccionado_seleccionado;
	}
	public void setSexo_seleccionado_seleccionado(String sexo_seleccionado_seleccionado) {
		this.sexo_seleccionado_seleccionado = sexo_seleccionado_seleccionado;
	}
	public String getGradoLesion_seleccionado() {
		return gradoLesion_seleccionado;
	}
	public void setGradoLesion_seleccionado(String gradoLesion_seleccionado) {
		this.gradoLesion_seleccionado = gradoLesion_seleccionado;
	}
	public String getMes_seleccionado() {
		return mes_seleccionado;
	}
	public void setMes_seleccionado(String mes_seleccionado) {
		this.mes_seleccionado = mes_seleccionado;
	}
	public String getDistrito_seleccionado() {
		return distrito_seleccionado;
	}
	public void setDistrito_seleccionado(String distrito_seleccionado) {
		this.distrito_seleccionado = distrito_seleccionado;
	}
	public String getVehiculo_seleccionado() {
		return vehiculo_seleccionado;
	}
	public void setVehiculo_seleccionado(String vehiculo_seleccionado) {
		this.vehiculo_seleccionado = vehiculo_seleccionado;
	}
	public String getIntervaloHora_seleccionado() {
		return intervaloHora_seleccionado;
	}
	public void setIntervaloHora_seleccionado(String intervaloHora_seleccionado) {
		this.intervaloHora_seleccionado = intervaloHora_seleccionado;
	}
	public String getWeather_seleccionado() {
		return weather_seleccionado;
	}
	public void setWeather_seleccionado(String weather_seleccionado) {
		this.weather_seleccionado = weather_seleccionado;
	}
	public String getN_results() {
		return n_results;
	}
	public void setN_results(String n_results) {
		this.n_results = n_results;
	}
	public static Controller getC() {
		return c;
	}
	public static void setC(Controller c) {
		Searcher.c = c;
	}
}
